---
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- with  .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- with .Values.ingress.rules }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  tls:
  {{- with .Values.ingress.tls }}
  {{- toYaml . | nindent 4 }}
  {{- end }}